apiVersion: v1
kind: Template
labels:
  template: monitoring demobackery
  group: demobackery
metadata:
  name: prometheus
  description: "Template containing prometheus artifacts."
parameters:
- displayName: project name
  value: dev-rcp-1
  name: PROJECT
  required: true
- displayName: Application name
  description: Name of the application
  name: APP_NAME
  required: true
  value: backerydemo
objects:
- apiVersion: integreatly.org/v1alpha1
  kind: Grafana
  metadata:
    name: grafana-instance
    namespace:  ${PROJECT}
    labels:
      name: grafana-instance
      app: grafana-app
      project:  ${PROJECT}
  spec:
    ingress:
      enabled: true
    config:
      auth:
        disable_signout_menu: true
      auth.anonymous:
        enabled: true
      log:
        level: warn
        mode: console
      security:
        admin_password: secret
        admin_user: root
    dashboardLabelSelector:
      - matchExpressions:
          - key: app
            operator: In
            values:
              - grafana-app
- apiVersion: integreatly.org/v1alpha1
  kind: GrafanaDataSource
  metadata:
    name: grafana-datasource
    namespace:  ${PROJECT}
    labels:
      name: grafana-datasource
      app: grafana-app
      project:  ${PROJECT}
  spec:
    name: grafana-datasource
    datasources:
      - access: proxy
        editable: true
        isDefault: true
        jsonData:
          timeInterval: 5s
        name: Prometheus
        type: prometheus
        url: 'http://prometheus-operated:9090'
        version: 1
        editable: true
        jsonData:
          tlsSkipVerify: true
          timeInterval: "5s"