apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    service: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.app_name }}
  sessionAffinity: None
  type: ClusterIP