kind: ConfigMap
apiVersion: v1
metadata:
  name: sonar-script
data:
  sonar.sh: >
    #!/bin/bash

    REPORTS=$1

    [  -z "$REPORTS" ] && REPORTS="target/sonar/report-task.txt"
    
    [[ ! -f "$REPORTS" ]] && \

    echo "$REPORTS does not exists or wrong path" && \

    exit -1;

    sonarUrl=$(cat target/sonar/report-task.txt | grep serverUrl | cut -f2- -d=)

    ceTaskUrl=$(cat target/sonar/report-task.txt | grep ceTaskUrl | cut -f2- -d=)

    dashboardUrl=$(cat target/sonar/report-task.txt | grep dashboardUrl | cut -f2- -d=)

    [  -z "$sonarUrl" ] && echo "sonarUrl is Empty" && exit -1

    [  -z "$ceTaskUrl" ] && echo "ceTaskUrl is Empty" && exit -1

    [  -z "$dashboardUrl" ] && echo "dashboardUrl is Empty" && exit -1

    curl -sf -H \"Accept: application/json\" --connect-timeout  5 -m 15 ${ceTaskUrl} > /tmp/sonar-results.json

    ceTaskStatus=$(cat /tmp/sonar-results.json | jq -r .[].status)

    analysisId=$(cat /tmp/sonar-results.json | jq -r .[].analysisId)

    while [ ${ceTaskStatus} == "PENDING" ] || [ ${ceTaskStatus} == "IN_PROGRESS"
    ]

    do
        echo "Status is ${ceTaskStatus}, Trying again in 20 seconds"
        sleep 20
        curl -sf -H \"Accept: application/json\" --connect-timeout  5 -m 15 ${ceTaskUrl} > /tmp/sonar-results.json
        ceTaskStatus=$(cat /tmp/sonar-results.json | jq -r .[].status)
        analysisId=$(cat /tmp/sonar-results.json | jq -r .[].analysisId)
    done


    if [ ${ceTaskStatus} == "CANCELED" ] || [ ${ceTaskStatus} == "FAILED" ];
    then
      echo "Build failed because sonar project is ${ceTaskStatus}"
      exit 1
    fi


    ## Second part

    analysisUrl="${sonarUrl}/api/qualitygates/project_status?analysisId=${analysisId}"

    curl -sf -H \"Accept: application/json\" --connect-timeout  5 -m 15
    ${analysisUrl} > sonar-analysis-results.json

    projectStatus=$(cat sonar-analysis-results.json | jq -r
    .projectStatus.status)


    if [[ ${projectStatus} == "OK" ]]; then
        echo "Huraaaah! You made it :) Sonar Results are good: ${dashboardUrl}"
    else
        echo "Hey Dude not cool :( you are supposed to improve your code quality. Quality Gate is NOT PASSED: ${dashboardUrl}"
        exit 1
    fi

    exit 0
