apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: {{ .Values.app_name }}-pipelineRun
  labels:
    tekton.dev/pipeline: build-and-deploy
spec:
  params:
    - name: APP_NAME
      value: demobakery
    - name: PROJECT_NAME
      value: bookinfo
    - name: GIT_CONTEXT_DIR_KUBERNETES
      value: kubernetes/dev
    - name: GIT_CONTEXT_DIR_DOCKER
      value: kubernetes/dev
    - name: WAR_CONTEXT
      value: ./target
    - name: IMAGE_URL
      value: image-registry.openshift-image-registry.svc:5000/bookinfo/demobakery
  pipelineRef:
    name: build-and-deploy
  serviceAccountName: pipeline
  serviceAccountNames:
    - taskName: build-image-task
      serviceAccountName: pipeline
  resources:
    - name: app-git
      resourceRef:
        name: app-git
  timeout: 1h0m0s
