apiVersion: v1
kind: Template
labels:
  template: cicd
  group: cicd
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: DemoBackery,jenkins,cdci
  name: cicd
message: "Use the following credentials for login:\nJenkins: use your OpenShift credentials\nApplication: admin@vaadin.com/admin"
parameters:
- displayName: DEV project name
  value: dev-demobakery
  name: DEV_PROJECT
  required: true
- displayName: PROD project name
  value: prod-demobakery
  name: PROD_PROJECT
  required: true
- description: Webhook secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: WEBHOOK_SECRET
  required: true
- displayName: Quay.io Image Repository
  description: Quay.io repository for pushing Tasks container images
  name: QUAY_REPOSITORY
  required: true
  value: demobakery
- displayName: Application name
  description: Name of the application
  name: APP_NAME
  required: true
- displayName: Application repository
  description: repository containing application code
  name: APP_REPO
  required: true
- displayName: Repository branch
  description: Code base branch
  name: APP_BRANCH
  required: true
- displayName: memory
  description: memory allocation
  name: MEMORY
  required: false
- displayName: cpu
  description: cpu allocation
  name: CPU
  required: false
- displayName: Application replicas
  description: number of application replicas
  name: REPLICAS
  required: false
- displayName: Images tag 
  description: tag of application image
  name: IMAGE_TAG
  required: false
objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: prod_admin
    namespace: ${PROD_PROJECT}
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ${DEV_PROJECT}