apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.app_name }}
    template: {{ .Chart.Name }}
  name: {{ .Values.app_name }}-test
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    app: {{ .Values.app_name }}
    version: {{ .Values.image_tag | trunc 7}}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
        version: {{ .Values.image_tag | trunc 7}}
    spec:
      containers:
      - image: {{ .Values.quay_repository }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        name: {{ .Values.app_name }}
        ports:
        - containerPort: 8080
          name: 8080-tcp
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP	
          periodSeconds: 10	
          successThreshold: 1	
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers: []
